# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='厂商名称')),
                ('tel', models.CharField(max_length=15, null=True, verbose_name='联系电话')),
                ('mail', models.EmailField(max_length=254, null=True, verbose_name='邮件地址')),
                ('remark', models.CharField(max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'resources_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='型号名称')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.Manufacturer', verbose_name='所属产品')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'resources_productmodel',
            },
        ),
    ]
