# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cabinet',
            field=models.ForeignKey(help_text='所在机柜', null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Cabinet', verbose_name='所在机柜'),
        ),
    ]
